When installing our big changes to context and architecture shift I updated the python libraries but the firmware build for Arduino failed. Here is the message:
Processing megaatmega2560_main (platform: atmelavr; board: megaatmega2560; framework: arduino)
----------------------------------------------------------------------------------
Verbose mode can be enabled via `-v, --verbose` option
CONFIGURATION: https://docs.platformio.org/page/boards/atmelavr/megaatmega2560.html
PLATFORM: Atmel AVR (5.1.0) > Arduino Mega or Mega 2560 ATmega2560 (Mega 2560)
HARDWARE: ATMEGA2560 16MHz, 8KB RAM, 248KB Flash
DEBUG: Current (avr-stub) External (avr-stub, simavr)
PACKAGES:
 - framework-arduino-avr @ 5.2.0
 - tool-avrdude @ 1.60300.200527 (6.3.0)
 - toolchain-atmelavr @ 1.70300.191015 (7.3.0)
LDF: Library Dependency Finder -> https://bit.ly/configure-pio-ldf
LDF Modes: Finder ~ chain, Compatibility ~ soft
Found 14 compatible libraries
Scanning dependencies...
Dependency Graph
|-- ModbusMaster @ 2.0.1
|-- Adafruit ADS1X15 @ 2.6.0
|-- Adafruit MAX31855 library @ 1.4.2
|-- Adafruit MCP4725 @ 2.0.2
|-- PID @ 1.2.1
|-- ArduinoJson @ 6.21.5
|-- HX711 @ 0.7.5
|-- EEPROM @ 2.0
|-- SPI @ 1.0
|-- Wire @ 1.0
Building in release mode
Compiling .pio/build/megaatmega2560_main/src/main.cpp.o
src/main.cpp: In function 'void loop()':
src/main.cpp:90:9: error: 'stepperFeed' was not declared in this scope
         stepperFeed.setFlowRate(cmd.value);
         ^~~~~~~~~~~
src/main.cpp:92:9: error: 'stepperAux' was not declared in this scope
         stepperAux.setFlowRate(cmd.value);
         ^~~~~~~~~~
*** [.pio/build/megaatmega2560_main/src/main.cpp.o] Error 1
=========================== [FAILED] Took 1.22 seconds ===========================

Environment             Status    Duration
----------------------  --------  ------------
megaatmega2560_scanner  SUCCESS   00:00:02.430
megaatmega2560_main     FAILED    00:00:01.218
===================== 1 failed, 1 succeeded in 00:00:03.648 =====================